include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: ignore
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
