name: database_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  clock: ^1.1.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
