name: supabase_database
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  database_client:
    path: ../database_client
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mock_supabase_http_client: ^0.0.3+2
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
